data "aws_caller_identity" "current" {}

locals {
  uc_role_name = "databricks-${var.environment}-uc-role"
}

# --- Cross-account role: the Databricks control plane assumes this role ---

data "databricks_aws_assume_role_policy" "this" {
  external_id = var.account_id
}

data "databricks_aws_crossaccount_policy" "this" {
  policy_type = "customer"
}

resource "aws_iam_role" "cross_account" {
  name                 = "databricks-${var.environment}-crossaccount-role"
  assume_role_policy   = data.databricks_aws_assume_role_policy.this.json
  max_session_duration = 3600

  tags = {
    Name        = "databricks-${var.environment}-crossaccount-role"
    Environment = var.environment
  }
}

resource "aws_iam_policy" "cross_account" {
  name   = "databricks-${var.environment}-crossaccount-policy"
  policy = data.databricks_aws_crossaccount_policy.this.json
}

resource "aws_iam_role_policy_attachment" "cross_account" {
  role       = aws_iam_role.cross_account.name
  policy_arn = aws_iam_policy.cross_account.arn
}

# --- Workspace root bucket ---

resource "aws_s3_bucket" "root" {
  bucket = "databricks-${var.environment}-root-${var.account_id}"

  tags = {
    Name        = "databricks-${var.environment}-root"
    Environment = var.environment
  }
}

resource "aws_s3_bucket_public_access_block" "root" {
  bucket = aws_s3_bucket.root.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "root" {
  bucket = aws_s3_bucket.root.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

data "databricks_aws_bucket_policy" "root" {
  bucket = aws_s3_bucket.root.bucket
}

resource "aws_s3_bucket_policy" "root" {
  bucket = aws_s3_bucket.root.id
  policy = data.databricks_aws_bucket_policy.root.json

  # Avoids a race between the public access block and the bucket policy
  depends_on = [aws_s3_bucket_public_access_block.root]
}

# --- Unity Catalog bucket + role ---

resource "aws_s3_bucket" "unity_catalog" {
  bucket = "databricks-${var.environment}-uc-${var.account_id}"

  tags = {
    Name        = "databricks-${var.environment}-uc"
    Environment = var.environment
  }
}

resource "aws_s3_bucket_public_access_block" "unity_catalog" {
  bucket = aws_s3_bucket.unity_catalog.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_server_side_encryption_configuration" "unity_catalog" {
  bucket = aws_s3_bucket.unity_catalog.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

data "aws_iam_policy_document" "unity_catalog_trust" {
  # Unity Catalog master role
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL"]
    }

    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [var.account_id]
    }
  }

  # Self-assuming role, required by Unity Catalog. The account root + ArnLike pattern
  # avoids an "Invalid principal" error, since the role does not exist yet at creation time.
  statement {
    sid     = "ExplicitSelfRoleAssumption"
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
    }

    condition {
      test     = "ArnLike"
      variable = "aws:PrincipalArn"
      values   = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.uc_role_name}"]
    }
  }
}

resource "aws_iam_role" "unity_catalog" {
  name               = local.uc_role_name
  assume_role_policy = data.aws_iam_policy_document.unity_catalog_trust.json

  tags = {
    Name        = local.uc_role_name
    Environment = var.environment
  }
}

# Access policy generated by Databricks (S3 access plus self-assume permission)
data "databricks_aws_unity_catalog_policy" "this" {
  aws_account_id = data.aws_caller_identity.current.account_id
  bucket_name    = aws_s3_bucket.unity_catalog.id
  role_name      = local.uc_role_name
}

resource "aws_iam_policy" "unity_catalog" {
  name   = "databricks-${var.environment}-uc-policy"
  policy = data.databricks_aws_unity_catalog_policy.this.json
}

resource "aws_iam_role_policy_attachment" "unity_catalog" {
  role       = aws_iam_role.unity_catalog.name
  policy_arn = aws_iam_policy.unity_catalog.arn
}

# --- Register the cross-account role with Databricks ---

resource "databricks_mws_credentials" "this" {
  credentials_name = "databricks-${var.environment}-crossaccount-creds"
  role_arn         = aws_iam_role.cross_account.arn

  depends_on = [aws_iam_role_policy_attachment.cross_account]
}